name: Packman
version: '0.4.2'
main: me.sekc.packman.Packman
description: Add custom content to your game!
api-version: '26.2'

dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false

bootstrapper: me.sekc.packman.PackmanBootstrapper