name: packman
version: '${version}'

main: me.sekc.packman.Packman
api-version: '26.1.2'
load: POSTWORLD

depend:
  - packetevents

authors: [ sekc ]

permissions:
  packman.give:
    description: Allows admins give themselves custom items.
    default: op
  packman.reload:
    description: Allows admins to re-generate the resource pack and reload configs.
    default: op